### ISSUE TITLE
SR-TE policy issue

### ISSUE THREAD

**Issue by redsky666** [nokia-t1zhou/segment-routing-step-by-step#2] opened 2020-05-03 04:35 UTC
你好：
       SR-TE policy这一步里，我的tunnel口起不来，我把我的配置和您的配置对了一下，也没有什么出入就是起不来，很奇怪，不知道是不是模拟器的问题，想请教一下您
RP/0/0/CPU0:R2#show mpls traffic-eng tunnels 
Sun May  3 04:59:36.172 UTC

Name: tunnel-te2  Destination: 192.168.100.10  Ifhandle:0x580 
  Signalled-Name: R2_t2
  Status:
    Admin:    up Oper: down   Path:  valid   Signalling: wait segment path

    path option 1, (Segment-Routing) type explicit path_2_4_5
      Protected-by PO index: none
    Last PCALC Error: Sun May  3 02:57:11 2020
      Info: No paths for prefix 1.1.1.4/32
    G-PID: 0x0800 (derived from egress interface properties)
    Bandwidth Requested: 0 kbps  CT0
    Creation Time: Sun May  3 02:54:15 2020 (02:05:21 ago)
  Config Parameters:
    Bandwidth:        0 kbps (CT0) Priority:  7  7 Affinity: 0x0/0x0
    Metric Type: TE (global)
    Path Selection:
      Tiebreaker: Min-fill (default)
    Hop-limit: disabled
    Cost-limit: disabled
    Path-invalidation timeout: 10000 msec (default), Action: Tear (default)
    AutoRoute:  enabled  LockDown: disabled   Policy class: not set
    Forward class: 0 (default)
    Forwarding-Adjacency: disabled
    Autoroute Destinations: 0
    Loadshare:          0 equal loadshares
    Auto-bw: disabled
    Fast Reroute: Disabled, Protection Desired: None
    Path Protection: Enabled
    BFD Fast Detection: Disabled
    Reoptimization after affinity failure: Enabled
    Soft Preemption: Disabled
  History:
    Current LSP:
      Setup Time: 2289 seconds
    Prior LSP:
      ID: 5 Path Option: 1
      Removal Trigger: path tear

  Segment-Routing Path Info (OSPF 1 area 1)
    Segment0[Node]: 1.1.1.4, Label: 16400
    Segment1[ - ]: Label: 16510
Displayed 1 (of 1) heads, 0 (of 0) midpoints, 0 (of 0) tails
Displayed 0 up, 1 down, 0 recovering, 0 recovered heads

**Comment by redsky666** [comment] 2020-05-03 08:09
解决了Segment-Routing Path Info **(OSPF 1 area 1)**，area为1了，吧area 1删掉，然后从新加上就好了，就变成了area 0了，有可能是模拟器bug

**Comment by nokia-t1zhou** [comment] 2020-05-06 01:29
我的理解，这里不管area1或者area0， 其实没多大区别，这个tunnels在area0和area1中都打开了，通过参数“mpls traffic-eng”控制。
会不会是“mpls traffic-eng”的配置顺序导致了显示问题？ 
目录“appliance”中有我使用的IOS image，你可以试试

**Comment by nokia-t1zhou** [comment] 2020-05-06 01:30
i think we can close this issue due to the problem is solved.

**Closed as completed by nokia-t1zhou** 2020-05-06 01:30 UTC
Labels: good first issue
